name: Salesforce Deployment Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate:
    name: Validate Deployment on PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI (sf)
        run: |
          npm install --global @salesforce/cli

      - name: Authenticate to Salesforce using Auth URL
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > sfdx_auth.txt
          sf org login sfdx-url -f sfdx_auth.txt -a DEPLOY_ORG

      - name: Validate Deploy (dry run + run all tests)
        run: |
          sf project deploy start \
            --manifest manifest/package.xml \
            --dry-run \
            --ignore-conflicts \
            --test-level RunLocalTests \
            --wait 30 \
            -o DEPLOY_ORG


  deploy:
    name: Deploy to Salesforce on Merge to Main
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI (sf)
        run: |
          npm install --global @salesforce/cli

      - name: Authenticate to Salesforce using Auth URL
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > sfdx_auth.txt
          sf org login sfdx-url -f sfdx_auth.txt -a DEPLOY_ORG

      - name: Deploy Source and run all tests
        run: |
          sf project deploy start \
            --manifest manifest/package.xml \
            --ignore-conflicts \
            --test-level RunLocalTests \
            --wait 30 \
            -o DEPLOY_ORG
deploy_uat:
    name: Deploy to UAT
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/uat'

    steps:
      - uses: actions/checkout@v4
      - run: npm install --global @salesforce/cli

      - name: Authenticate to UAT
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_UAT }}
        run: |
          echo "$SFDX_AUTH_URL" > sfdx_auth.txt
          sf org login sfdx-url -f sfdx_auth.txt -a UAT

      - name: Deploy to UAT
        run: |
          sf project deploy start \
            --manifest manifest/package.xml \
            --ignore-conflicts \
            --test-level RunLocalTests \
            --wait 30 \
            -o UAT
